from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def render_app(papers: list[dict[str, Any]], stats: dict[str, Any], output_path: Path,
               profile_name: str, coverage: dict[str, str]) -> Path:
    output_path.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(papers, ensure_ascii=False).replace("<", "\\u003c")
    page = f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Frontier App · {html.escape(profile_name)}</title><style>
body{{font-family:-apple-system,"Segoe UI","Microsoft YaHei",sans-serif;background:#f2f5f9;color:#172033;margin:0}}header{{background:#12395a;color:white;padding:22px;position:sticky;top:0;z-index:2}}main{{max-width:1100px;margin:auto;padding:20px}}.tools{{display:flex;gap:10px;flex-wrap:wrap}}input,select,textarea{{padding:8px;border:1px solid #cad3df;border-radius:7px}}#q{{flex:1;min-width:260px}}article{{background:white;margin:12px 0;padding:18px;border-radius:12px;border-left:5px solid #678;box-shadow:0 1px 8px #20305014}}article[data-priority=A]{{border-color:#d4380d}}article[data-priority=B]{{border-color:#d48806}}article[data-priority=C]{{border-color:#1677ff}}.meta{{color:#6b778c;font-size:.88em}}.feedback{{display:grid;grid-template-columns:110px 150px 1fr;gap:8px;margin-top:12px}}textarea{{grid-column:1/-1;min-height:60px}}button{{padding:8px 13px;border:0;border-radius:7px;background:#1677ff;color:white;cursor:pointer}}@media(max-width:700px){{.feedback{{grid-template-columns:1fr}}textarea{{grid-column:auto}}}}
</style></head><body><header><h1>Frontier App · {html.escape(profile_name)}</h1><div>{coverage.get('from','')} → {coverage.get('to','')} · {stats.get('scanned',0)} scanned · {stats.get('candidates',0)} candidates</div></header><main><div class="tools"><input id="q" placeholder="搜索标题、主题、项目"><select id="priority"><option value="">全部优先级</option><option>A</option><option>B</option><option>C</option><option>D</option><option>Ignore</option></select><button onclick="downloadFeedback()">导出 feedback.json</button></div><div id="list"></div></main><script>
const papers={payload}; const profile={json.dumps(profile_name)}; const statuses=['new','saved','reading','read','ignored','cited'];
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}}[c]));
const key=p=>'feedback:'+profile+':'+p.paper_id; const load=p=>JSON.parse(localStorage.getItem(key(p))||'{{}}');
function save(p,id){{const value={{paper_id:p.paper_id,stable_id:p.stable_id,rating:Number(document.getElementById('r'+id).value)||null,reading_status:document.getElementById('s'+id).value,note:document.getElementById('n'+id).value,related_project:document.getElementById('j'+id).value,timestamp:new Date().toISOString()}};localStorage.setItem(key(p),JSON.stringify(value));}}
function render(){{const q=document.getElementById('q').value.toLowerCase(), pr=document.getElementById('priority').value;const rows=papers.filter(p=>(!pr||p.priority===pr)&&(!q||[p.title,p.title_cn,p.research_track,p.related_project,p.matched_keywords].join(' ').toLowerCase().includes(q)));document.getElementById('list').innerHTML=rows.map((p,i)=>{{const f=load(p), opts=statuses.map(s=>`<option ${{(f.reading_status||p.reading_status||'new')===s?'selected':''}}>${{s}}</option>`).join('');return `<article data-priority="${{esc(p.priority)}}"><b>${{esc(p.priority)}} · ${{esc(p.relevance_score)}}/100</b><h2>${{esc(p.title_cn||p.title)}}</h2><div>${{esc(p.title)}}</div><p class="meta">${{esc(p.venue||p.journal)}} · ${{esc(p.related_project||'No project')}}</p><p><b>Why:</b> ${{esc(p.why_relevant)}}</p><p><b>Use:</b> ${{esc(p.potential_use)}}</p><div class="feedback"><select id="r${{i}}" onchange="save(papers.find(x=>x.paper_id===${{p.paper_id}}),${{i}})"><option value="">评分</option>${{[1,2,3,4,5].map(r=>`<option ${{Number(f.rating)===r?'selected':''}}>${{r}}</option>`).join('')}}</select><select id="s${{i}}" onchange="save(papers.find(x=>x.paper_id===${{p.paper_id}}),${{i}})">${{opts}}</select><input id="j${{i}}" value="${{esc(f.related_project||p.related_project||'')}}" placeholder="related project" onchange="save(papers.find(x=>x.paper_id===${{p.paper_id}}),${{i}})"><textarea id="n${{i}}" placeholder="阅读笔记" onchange="save(papers.find(x=>x.paper_id===${{p.paper_id}}),${{i}})">${{esc(f.note||'')}}</textarea></div></article>`}}).join('')}}
function downloadFeedback(){{const data=papers.map(load).filter(x=>Object.keys(x).length);const blob=new Blob([JSON.stringify({{profile,feedback:data}},null,2)],{{type:'application/json'}});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='feedback.json';a.click();URL.revokeObjectURL(a.href)}}
document.getElementById('q').oninput=render;document.getElementById('priority').onchange=render;render();</script></body></html>"""
    (output_path / "index.html").write_text(page, encoding="utf-8")
    return output_path
