from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from .common import POOL_LABELS, PRIORITY_LABELS


def _value(paper: dict[str, Any], key: str, fallback: str = "") -> str:
    value = paper.get(key, fallback)
    if isinstance(value, list):
        value = "; ".join(str(item) for item in value)
    return html.escape(str(value or fallback))


def render_report(data: dict[str, Any], output_path: Path) -> Path:
    profile = data["profile"]
    stats = data["stats"]
    papers = data["report_papers"]
    top_five = sorted(papers, key=lambda p: p.get("relevance_score", 0), reverse=True)[:5]

    def card(p: dict[str, Any]) -> str:
        priority = p.get("priority", "D")
        doi = p.get("doi_url", "")
        title = _value(p, "title", "Untitled")
        title_link = f'<a href="{html.escape(doi)}" target="_blank" rel="noopener">{title}</a>' if doi else title
        contributions = "".join(f"<li>{html.escape(str(item))}</li>" for item in p.get("main_contributions", []))
        return f"""<article class="paper p-{priority}">
<div class="badges"><span class="priority">{PRIORITY_LABELS.get(priority, priority)}</span><span>Relevance {p.get('relevance_score', 0)}/100</span><span>{_value(p, 'research_track')}</span><span>{_value(p, 'related_project', 'No project')}</span></div>
<h3>{title_link}</h3><h4>{_value(p, 'title_cn')}</h4>
<p class="meta">{_value(p, 'venue', p.get('journal', ''))} · {_value(p, 'publication_date')} · {_value(p, 'authors')}</p>
<section><b>一句话推荐 / Why relevant</b><p>{_value(p, 'why_relevant', 'Not analyzed')}</p></section>
<section><b>Research Question</b><p>{_value(p, 'research_question', 'Not available')}</p></section>
<section><b>Method</b><p>{_value(p, 'method_summary', 'Not available')}</p></section>
<section><b>Main Contributions</b><ul>{contributions or '<li>Not available</li>'}</ul></section>
<section><b>Potential Use</b><p>{_value(p, 'potential_use', 'Not available')}</p></section>
<section><b>Recommended Action</b><p>{_value(p, 'recommended_action')}</p></section>
<details><summary>Abstract EN / 中文摘要</summary><p>{_value(p, 'abstract')}</p><p>{_value(p, 'abstract_cn')}</p></details>
<p class="keywords">Matched: {_value(p, 'matched_keywords')} · Keyword tier: {_value(p, 'keyword_tier')} · Semantic: {_value(p, 'semantic_score', 'disabled')}</p>
</article>"""

    top_html = "".join(
        f"<li><b>{_value(p, 'title')}</b> — {_value(p, 'why_relevant', 'Keyword recall candidate')}</li>"
        for p in top_five
    ) or "<li>No candidates in this window.</li>"
    cards = "".join(card(paper) for paper in papers)
    content = f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Weekly Research Brief · {html.escape(profile['name'])}</title><style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;background:#f5f7fb;color:#172033;max-width:1080px;margin:auto;padding:24px;line-height:1.65}}header,.paper{{background:white;border-radius:14px;padding:22px;margin:14px 0;box-shadow:0 2px 12px #20305014}}h1{{margin:.1em 0}}.summary{{display:flex;flex-wrap:wrap;gap:10px}}.summary span,.badges span{{background:#eef3fb;border-radius:999px;padding:5px 11px;font-size:.88em}}.paper{{border-left:6px solid #94a3b8}}.p-A{{border-color:#d4380d}}.p-B{{border-color:#d48806}}.p-C{{border-color:#1677ff}}.p-D{{border-color:#64748b}}.badges{{display:flex;flex-wrap:wrap;gap:7px}}h3{{margin-bottom:0}}h4{{margin:.15em 0;color:#38536f}}a{{color:#135f9b;text-decoration:none}}.meta,.keywords{{color:#6b778c;font-size:.88em}}section p{{margin-top:.2em}}details{{background:#f8fafc;padding:10px;border-radius:8px}}footer{{text-align:center;color:#7d8899;margin:30px}}
</style></head><body><header><h1>Weekly Research Brief</h1><p>Profile: <b>{html.escape(profile['name'])}</b> · {html.escape(data['coverage']['from'])} → {html.escape(data['coverage']['to'])}</p>
<div class="summary"><span>本周扫描 {stats['scanned']}</span><span>候选 {stats['candidates']}</span><span>A Must Read {stats.get('A',0)}</span><span>B Method {stats.get('B',0)}</span><span>C Frontier {stats.get('C',0)}</span></div>
<h2>Top 5 推荐</h2><ol>{top_html}</ol></header>{cards}<footer>Generated by Personal Research Frontier Agent · Data from configured providers; judgments should be verified by the reader.</footer></body></html>"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path
